int8 START = 1
int8 STOP = 0

int8 command # START or STOP
string filename
int8 fps # default = 15
string codec # default = "MJPG"
string encoding # default = "bgr8"
string topic # default = image
---
bool ok
string message
